services:
  django:
    build: .
    container_name: tews_crm
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS= *
      - DATABASE_URL=sqlite:////usr/src/app/db.sqlite3
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
  celery:
    build: .
    # command: celery worker --app=tews_crm --loglevel=info
    command: celery -A tews_crm worker -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
  celery_beat:
    build: .
    # command: celery worker --app=tews_crm --loglevel=info
    command: celery -A tews_crm beat -l INFO
    volumes:
      - .:/usr/src/app/
    depends_on:
      - django
      - redis
      - celery
  # pgdb:
  #   image: postgres
  #   container_name: pgdb
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
volumes:
  pgdata:
