# Generated by Django 5.0.4 on 2024-04-25 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(default='none', max_length=250)),
                ('title', models.TextField(default='none')),
                ('subtitle', models.TextField(default='none')),
                ('content', models.TextField(default='none')),
                ('conclusion', models.TextField(default='none')),
                ('category', models.CharField(default='none', max_length=250)),
                ('subcategory', models.CharField(default='none', max_length=250)),
                ('tags', models.TextField()),
                ('author', models.CharField(default='Max', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('image_path', models.CharField(default='none', max_length=250)),
            ],
            options={
                'verbose_name_plural': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_id', models.CharField(default='none', max_length=250)),
                ('url', models.CharField(default='none', max_length=250)),
                ('title', models.CharField(default='none', max_length=250)),
                ('sub_title', models.CharField(default='none', max_length=250)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(100)])),
                ('category', models.CharField(default='none', max_length=100)),
                ('sub_category', models.CharField(default='none', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'ScrapedPost',
            },
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(default='none', max_length=250)),
                ('urls', models.JSONField(default=list)),
                ('is_generated', models.BooleanField(default=False)),
                ('in_process', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'URL',
            },
        ),
    ]
