# Generated by Django 5.0.4 on 2024-04-26 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='is_scraped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='content',
            field=models.TextField(default='none', validators=[django.core.validators.MinLengthValidator(100)]),
        ),
    ]
