# Generated by Django 5.0.4 on 2024-04-26 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_scrape_is_scraped_alter_scrape_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrape',
            options={'verbose_name_plural': 'Scrape'},
        ),
    ]
