# Generated by Django 5.0.4 on 2024-04-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_scrape_category_alter_scrape_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='is_join_ready',
            field=models.BooleanField(default=False),
        ),
    ]
