# Generated by Django 5.0.4 on 2024-04-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_scrape_is_join_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_prompt',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('predraft', 'PreDraft'), ('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='predraft', max_length=10),
        ),
    ]
