# Generated by Django 5.0.4 on 2024-04-27 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_post_selected_image_alter_post_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='in_process',
        ),
        migrations.RemoveField(
            model_name='url',
            name='is_generated',
        ),
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.CharField(default='In Process', max_length=25),
        ),
    ]
