# Generated by Django 5.0.4 on 2024-04-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_remove_url_in_process_remove_url_is_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.CharField(default='In Process', max_length=50),
        ),
    ]
