# Generated by Django 5.0.4 on 2024-04-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_url_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrape',
            name='is_join_ready',
        ),
        migrations.AddField(
            model_name='scrape',
            name='status',
            field=models.CharField(default='Not Join Ready', max_length=30),
        ),
    ]
