# Generated by Django 5.0.4 on 2024-04-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_remove_scrape_is_join_ready_scrape_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(default='Pre Draft', max_length=30),
        ),
    ]
