# Generated by Django 5.0.4 on 2024-04-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrape',
            name='is_scraped',
        ),
        migrations.AlterField(
            model_name='scrape',
            name='status',
            field=models.CharField(default='Not Scraped', max_length=30),
        ),
    ]
