# Generated by Django 5.0.4 on 2024-04-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_remove_scrape_is_scraped_alter_scrape_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='selected_image',
        ),
        migrations.AddField(
            model_name='post',
            name='image_data',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
