# Generated by Django 5.0.4 on 2024-04-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_remove_post_selected_image_post_image_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_id', models.CharField(default='none', max_length=250)),
                ('content', models.JSONField(default=list)),
                ('status', models.CharField(default='In Process', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'TwitterPost',
            },
        ),
    ]
