# Generated by Django 5.0.4 on 2024-04-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_twitterpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterpost',
            name='content',
            field=models.TextField(default='NoNE'),
        ),
        migrations.AlterField(
            model_name='twitterpost',
            name='status',
            field=models.CharField(default='No Tweet', max_length=50),
        ),
    ]
