# Generated by Django 5.0.4 on 2024-04-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_trending_remove_scrape_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='URL',
        ),
        migrations.AddField(
            model_name='scrape',
            name='count',
            field=models.TextField(default='NoNE'),
        ),
    ]
