# Generated by Django 5.0.4 on 2024-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_remove_scrape_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path_static',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
