# Generated by Django 5.0.4 on 2024-05-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_post_survey_alter_post_tags_alter_scrape_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_path_static',
            new_name='image_crm',
        ),
        migrations.AddField(
            model_name='post',
            name='all_image_data',
            field=models.TextField(default='none'),
        ),
    ]
