# Generated by Django 5.0.4 on 2024-05-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_post_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='trending',
            name='source',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
