# Generated by Django 5.0.4 on 2024-05-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_trending_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='short_content',
            field=models.TextField(default='none'),
        ),
    ]
