# Generated by Django 5.0.4 on 2024-05-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_post_rep_count_scrape_rep_count_trending_rep_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='all_image_data',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default=[], max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='conclusion',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.CharField(default=[], max_length=250),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='survey',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='content',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='images',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='title',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='scrape',
            name='url',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='trending',
            name='related_query_rising',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='trending',
            name='related_query_top',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='trending',
            name='related_topics_rising',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='trending',
            name='related_topics_top',
            field=models.TextField(default=[]),
        ),
    ]
