# Generated by Django 5.0.4 on 2024-05-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_post_all_image_data_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_crm',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_data',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_path',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_prompt',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.TextField(default=[]),
        ),
    ]
