# Generated by Django 5.0.4 on 2024-05-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_alter_post_category_alter_post_image_crm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Max', max_length=50),
        ),
    ]
